name: cookbook-api
dependencies:
  - python=3.12.3
  - pip=24.0
  - pip:
      - django==5.0.6
      - djangorestframework==3.15.1
      - djangorestframework_simplejwt==5.3.1
      - drf-yasg==1.21.7
      - pillow==10.3.0
      - django-dotenv==1.4.2
      - psycopg2_binary==2.9.9
      - django-cors-headers==4.3.1
      - gunicorn==22.0.0
      - dj-database-url==2.2.0
      - whitenoise==6.6.0
      - boto3==1.34.127
      - django_storages==1.14.3

